site_name: '🌱: `xmod`: Turn any object into a module 🌱'

theme:
  name: material

  palette:
    primary:
      'indigo'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
