[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py37']

[tool.doks]
auto = true

[tool.poetry]
name = "xmod"
version = "1.3.2"
description = "🌱 Create and recursively fill a temporary directory 🌱"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
dek = "^1.0.2"

[tool.poetry.group.dev.dependencies]
coverage = "^7.1.0"
flake8 = "5.0.4"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
